Model Training

In [14]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
# modelling
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.model_selection import train_test_split,GridSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor    
import warnings

In [15]:
df=pd.read_csv('data/Stud.csv')

In [16]:
df.head()

   gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [17]:
x=df.drop(['math score'],axis=1 )

In [18]:
x.head()

   gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 7 columns]

In [19]:
y=df['math score']
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

In [20]:
num_features=x.select_dtypes(exclude="object").columns
cat_features=x.select_dtypes(include="object").columns  

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numerical_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numerical_transformer,num_features)
    ]
)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_22344\3228735014.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features=x.select_dtypes(include="object").columns

In [21]:
x=preprocessor.fit_transform(x)

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((800, 19), (200, 19))

In [23]:
def evaluate_model(ture,predicted):
    mae=mean_absolute_error(ture,predicted)
    mse=mean_squared_error(ture,predicted)
    rmse=np.sqrt(mse)
    r2_square=r2_score(ture,predicted)
    return mae,mse,rmse,r2_square

In [24]:
models={
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "K-Neighbors":KNeighborsRegressor(),
    "DecisionTree":DecisionTreeRegressor(),
    "RandomForest":RandomForestRegressor(),
    "XGBRegressor":XGBRegressor(),
    "CatBoostRegressor":CatBoostRegressor(verbose=False),
    "AdaBoostRegressor":AdaBoostRegressor(),
}
model_list=[]
r2_list=[]
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)

    model_train_mae,model_train_mse,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_pred)
    model_test_mae,model_test_mse,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_pred)
    
    print('Model performance for',list(models.keys())[i])
    print('Train R2:', model_train_r2)
    print('Test R2:', model_test_r2)
    print('---')
    model_list.append(list(models.keys())[i])
    r2_list.append(model_test_r2)

Model performance for LinearRegression
Train R2: 0.8743172040139593
Test R2: 0.8804332983749565
---
Model performance for Ridge
Train R2: 0.8743042615212909
Test R2: 0.8805931485028737
---
Model performance for Lasso
Train R2: 0.8071462015863455
Test R2: 0.8253197323627852
---
Model performance for K-Neighbors
Train R2: 0.8554978341651085
Test R2: 0.7838129945787431
---
Model performance for DecisionTree
Train R2: 0.9996534669718089
Test R2: 0.7260604984663332
---
Model performance for RandomForest
Train R2: 0.9760353025755716
Test R2: 0.8514929803145423
---
Model performance for XGBRegressor
Train R2: 0.9954995512962341
Test R2: 0.8277965784072876
---
Model performance for CatBoostRegressor
Train R2: 0.9589358676277713
Test R2: 0.8516318920747058
---
Model performance for AdaBoostRegressor
Train R2: 0.8481721186167532
Test R2: 0.8543872899869792
---